version: '3'
services:
  shiny:
    image: rocker/shiny:latest
    ports:
      - "3838:3838"
    volumes:
      - ./shiny-app:/srv/shiny-server
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shinyapp
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
